# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bash-config = {
    pname = "bash-config";
    version = "f88071e92523a271dd553a20e60c8afaaf2dae0b";
    src = fetchFromGitHub {
      owner = "pestctrl";
      repo = "bash-config";
      rev = "f88071e92523a271dd553a20e60c8afaaf2dae0b";
      fetchSubmodules = false;
      sha256 = "sha256-+gQ28icbsv2+Jmxvm02OYWKCuFqtUoAdjDmWt3YgjKI=";
    };
    date = "2024-07-13";
  };
}
